server:
  port: 8082
spring:
  config:
    import: "file:config/config.yml"
  application:
    name: crypto-withdrawal
logging:
  level:
    root: INFO
    tgb.cryptoexchange: DEBUG
    org.springframework.boot.context.config: DEBUG
  file:
    name: logs/cryptowithdrawal.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
jwt:
  privateKeyPath: "file:config/private.key"
  publicKeyPath: "file:config/public.key"
  tokenExpirationMs: 3600000