security:
  username: "rce"
  password: "12345678"
isDev: true
minSum: true
turn:
  BITCOIN: true
  LITECOIN: true
credentials:
  BITCOIN:
    rpcUser: "user"
    rpcPassword: ""
url:
  BITCOIN: ""
  LITECOIN: ""